# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Java version
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Flutter version
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: Flutter Stable
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: flutter channel stable

      - name: Flutter Upgrade
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: flutter upgrade

      - name: Flutter Pub Get
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: flutter pub get

      - name: Check Flutter and Dart versions
        run: |
          flutter --version
          DART_PATH=$(dirname $(which dart))
          echo "DART_PATH=$DART_PATH" >> $GITHUB_ENV

      - name: Create a dummy .prod.env file
        run: echo -e "var BASE_URL = ''; \n var SENTRY_URL = ''; \nvar INIT_TOKEN = '';" > .prod.env

      - name: Create a dummy .staging.env file
        run: echo -e "var BASE_URL = ''; \n var SENTRY_URL = ''; \nvar INIT_TOKEN = '';" > .staging.env

      - name: Flutter clean and pub get
        run: flutter clean && flutter pub get

      - name: Run Riverpod generator
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Run Pigeon generator
        run: flutter pub run pigeon --input pigeon_conf.dart

      - name: Analyze
        run: flutter analyze . || exit $(( $? == 1 ? 0 : $? ))
        # This command runs Flutter analyze and exits with 0 if there are only warnings or infos,
        # allowing the workflow to continue. It will still fail on actual errors.
